import './App.css';
import "milligram";
import {useNavigate} from "react-router-dom";

const Home = () => {
    const navigate = useNavigate();

    return (
        <>
            <div className="container2">
                <div className="top-row2">
                    <div className="box3">
                        <ol>
                            <li>
                                <strong>Required:</strong>
                                <ul>
                                    <li>movies adding</li>
                                    <li>movies removal</li>
                                </ul>
                            </li>

                            <li>
                                <strong>Nice to have:</strong>
                                <ul>
                                    <li>actors to movie assignment</li>
                                </ul>
                            </li>

                            <li>
                                <strong>Extra:</strong>
                                <ul>
                                    <li>displaying actors, adding, removal</li>
                                    <li>router functionality</li>
                                    <li>layout functionality</li>
                                    <li>animation during loading response from server</li>
                                </ul>
                            </li>
                        </ol>
                    </div>
                    <div className="box3"><img src="/main_img.png" alt="Generated by Nano Banana Pro"/></div>
                </div>
                <div className="bottom-row2">
                    <div className="box3">
                        <div className="button-group">
                            <button onClick={() => navigate("/Movies")}>Movies Base</button>
                            <button onClick={() => navigate("/Actors")}>Actors Base</button>
                        </div>
                    </div>
                </div>
            </div>

        </>
    );
};

export default Home;