import './App.css';
import "milligram";
import {useNavigate} from "react-router-dom";
import main_img from './assets/main_img.png';

const Home = () => {
    const navigate = useNavigate();

    return (
        <>
            <div className="container2">
                <div className="top-row2">
                    <div className="box3">
                        <strong>Required (3.0): </strong>
                        <dl>
                            <dt>movies adding</dt>
                            <dt>movies removal</dt>
                        </dl>
                        <br />
                        <strong>Nice to have (4.0):</strong>
                        <dl>
                            <dt>actors to movie assignment</dt>
                        </dl>
                        <br />
                        <strong>Extra (5.0):</strong>
                        <dl>
                            <dt>displaying actors, adding, removal</dt>
                            <dt>added links to social media platforms</dt>
                            <dt>router functionality</dt>
                            <dt>layout functionality</dt>
                            <dt>animation during loading response from server</dt>
                        </dl>
                    </div>
                    <div className="box3"><img src={main_img} alt="Generated by Nano Banana Pro"/></div>
                </div>
                <div className="bottom-row2">
                    <div className="box3">
                        <div className="button-group">
                            <button onClick={() => navigate("/Movies")}>Movies Base</button>
                            <button onClick={() => navigate("/Actors")}>Actors Base</button>
                        </div>
                    </div>
                </div>
            </div>

        </>
    );
};

export default Home;